# Generated by Django 6.0 on 2026-01-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_subscriptionpack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
