# Generated by Django 6.0 on 2026-01-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_plantype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
