# Generated by Django 6.0 on 2026-01-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_plantype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpack',
            name='max_images_per_gig',
            field=models.PositiveBigIntegerField(),
        ),
    ]
