# Generated by Django 6.0 on 2026-01-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_usersubscription_subscriptiontransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpack',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
