# Generated by Django 6.0 on 2026-01-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0007_subscriptionpack_is_current"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
