# Generated by Django 6.0 on 2026-01-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0008_alter_usersubscription_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptiontransaction",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                ],
                max_length=50,
            ),
        ),
    ]
