# Generated by Django 6.0 on 2026-01-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0009_alter_subscriptiontransaction_payment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionpack",
            name="is_current",
        ),
    ]
