# Generated by Django 6.0 on 2026-01-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0011_usersubscription_connection_limit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubscription",
            name="gig_image_count",
        ),
    ]
