# Generated by Django 6.0 on 2026-01-12 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_subscriptionpack_max_images_per_gig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='connection_limit',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='gig_count',
        ),
        migrations.CreateModel(
            name='Total_pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_count', models.IntegerField(default=0)),
                ('connection_limit', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_pack', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
