# Generated by Django 6.0 on 2025-12-15 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='card_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.card')),
            ],
        ),
    ]
