# Generated by Django 6.0 on 2025-12-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_card_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
