# Generated by Django 6.0 on 2025-12-16 11:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_remove_card_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='haha', editable=False, populate_from='title', unique=True),
        ),
    ]
