# Generated by Django 6.0 on 2025-12-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_card_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='slug',
        ),
    ]
