# Generated by Django 6.0 on 2025-12-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_alter_card_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='skills_required',
            field=models.JSONField(),
        ),
    ]
