# Generated by Django 6.0 on 2026-01-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0021_wallettransactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
