# Generated by Django 6.0 on 2026-01-04 21:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_wallet_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
