# Generated by Django 6.0 on 2026-01-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_rating_created_at"),
        ("freelancer", "0012_alter_connections_client_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("reviewer", "gig", "freelancer")},
        ),
    ]
