# Generated by Django 6.0 on 2026-01-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_rating_unique_together'),
        ('freelancer', '0012_alter_connections_client_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('reviewer', 'gig')},
        ),
    ]
