# Generated by Django 6.0 on 2026-01-23 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_rating_unique_together"),
        ("client", "0023_categories_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="card",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card",
                to="client.card",
            ),
            preserve_default=False,
        ),
    ]
