# Generated by Django 6.0 on 2026-01-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_rating_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="freelancer",
            new_name="reviewee",
        ),
    ]
