# Generated by Django 6.0 on 2026-01-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freelancer", "0005_rating"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together=None,
        ),
        migrations.RemoveConstraint(
            model_name="rating",
            name="stars_between_1_and_5",
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
