# Generated by Django 6.0 on 2026-01-18 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelancer", "0006_alter_rating_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="connections",
            name="client_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_client",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
