# Generated by Django 6.0 on 2026-01-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freelancer", "0009_alter_connections_client_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connections",
            name="client_user",
        ),
    ]
